spring.application.name=synoptiq

##############################
# SERVER
##############################

server.port=${PORT:8080}

##############################
# DATABASE
##############################

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

##############################
# JWT
##############################

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

##############################
# GOOGLE LOGIN
##############################

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}

spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}

spring.security.oauth2.client.registration.google.scope=openid,email,profile,https://www.googleapis.com/auth/gmail.readonly

spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/google

spring.security.oauth2.client.provider.google.user-name-attribute=sub

##############################
# OPENAI
##############################

openai.api.key=${OPENAI_API_KEY}
openai.api.url=https://api.openai.com/v1/chat/completions


# VERCEL

frontend.url=${FRONTEND_URL}

# DEBUG

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never