spring.application.name=synoptiq

server.port=${PORT:8081}

spring.datasource.url=jdbc:postgresql://ep-plain-heart-awrrop5t-pooler.c-12.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_A5b3msyXLOdZ

openai.api.key=${OPENAI_API_KEY}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

openai.api.key=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
openai.api.url=https://api.openai.com/v1/chat/completions

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs

spring.main.allow-bean-definition-overriding=true
